version: '3.8'

services:
  synthea:
    build: 
      context: .
      dockerfile: ./infrastructure/synthea.Dockerfile
    image: synthea-devel:0.0.1
    command: java -jar ./synthea.jar --exporter.csv.export=true -p 5
    volumes:
      - ./output:/app/output 
      - ./infrastructure/config:/config
  postgres:
    build:
      context: .
      dockerfile: ./infrastructure/postgres.Dockerfile 
    restart: always
    image: postgres-devel
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PSQL_READONLY_PW=${PSQL_READONLY_PW}
      - PSQL_USER1_PW=${PSQL_USER1_PW}
    volumes: 
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - etlapp
  etl:
    build:
      context: .
      dockerfile: ./infrastructure/etl.Dockerfile
    depends_on:
      synthea:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    links:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: synthea-etl:0.0.1
    volumes:
      - ./output:/tmp/synthea/output
    networks:
      - etlapp

volumes:
  psql:
networks:
  etlapp:

