#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER user1 with PASSWORD '$PSQL_USER1_PW';
        CREATE USER readonly with PASSWORD '$PSQL_READONLY_PW';

        CREATE SCHEMA CdmSchema;
        CREATE SCHEMA native;
        GRANT USAGE ON SCHEMA CdmSchema TO user1; 
        GRANT USAGE ON SCHEMA CdmSchema TO readonly; 
        ALTER DEFAULT PRIVILEGES IN SCHEMA CdmSchema GRANT SELECT ON TABLES TO readonly;
        ALTER DEFAULT PRIVILEGES IN SCHEMA CdmSchema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user1;
EOSQL