#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER user1 with PASSWORD '$PSQL_USER1_PW';
        CREATE USER readonly with PASSWORD '$PSQL_READONLY_PW';

        CREATE SCHEMA cdm;
        ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT SELECT ON TABLES TO readonly;
        ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user1;
EOSQL